Feature/date range
fp-rap-build/front-end pull request #111
Opened 2021-04-15 18:29 UTC by ChristopherHarwell

2021-04-16 02:53 UTC, iesous-kurios requested changes
Think we should separate the 'powered by family promise' from the date range feature so we can merge them separately

2021-04-16 02:53 UTC, iesous-kurios commented on src/components/Layout/index.tsx
> +      <div>
Not sure this is the best way, it shows up weird on my screen

<img width="1680" alt="Screen Shot 2021-04-15 at 7 51 00 PM" src="https://user-images.githubusercontent.com/11794794/114964700-14359800-9e24-11eb-8a70-4a230e847e4e.png">

2021-04-22 20:58 UTC, ChristopherHarwell commented on src/components/Layout/index.tsx
> +      <div>
Forgot about this but just fixed it.

2021-04-22 22:00 UTC, iesous-kurios approved these changes
None breaking, plus this isn't the production/dev site anymore, so no repercussions!

2021-04-22 22:01 UTC, merged